apiVersion: apps/v1
kind: Deployment
metadata:
  name: rickandmorty-deployment
  namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rickandmorty
  template:
    metadata:
      labels:
        app: rickandmorty
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: rickandmorty
          image: felipeyorick/rickandmorty:161686e80ffef5cd9d87777a03280f1dcb4b75e2
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: mongo-secret
 
 