apiVersion: apps/v1
kind: Deployment
metadata:
  name: rickandmorty-deployment
  namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rickandmorty
  template:
    metadata:
      labels:
        app: rickandmorty
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: rickandmorty
          image: felipeyorick/rickandmorty:46f01590cb2aa2cb4e45e8d2081e067d34990eac
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: mongo-secret
 
 