apiVersion: apps/v1
kind: Deployment
metadata:
  name: rickandmorty-deployment
  namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rickandmorty
  template:
    metadata:
      labels:
        app: rickandmorty
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: rickandmorty
          image: felipeyorick/rickandmorty:e6dd7550dec98487ba35643e36f86e30db9443f6
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: mongo-secret
 
 