apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:1.18.0   # versión estable
          args:
            - "server"
            - "-config=/vault/config/vault.hcl"
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: "root"   # ⚠️ solo pruebas
          ports:
            - containerPort: 8200
              name: http
          volumeMounts:
            - name: config
              mountPath: /vault/config
            - name: data
              mountPath: /vault/data
      volumes:
        - name: config
          configMap:
            name: vault-config
        - name: data
          emptyDir: {}  # ⚠️ no persistente, usa PVC en prod