apiVersion: v1
kind: Service
metadata:
  name: vault-nodeport
  namespace: vault
spec:
  type: NodePort
  ports:
    - port: 8200
      targetPort: 8200
      nodePort: 30200
      protocol: TCP
      name: http
  selector:
    app: vault